name: Run posters script

on:
  schedule:
    - cron: '59 23 * * 4' # Run every Thursday at 11:59 PM

jobs:
  run_posters:
    runs-on: ubuntu-latest

    env:  # Add the environment variable here
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - name: Set up GitHub CLI
        run: |
          echo "machine github.com login $GH_TOKEN" > ~/.netrc
          gh config set prompt disabled

      - name: Update omigroup
        run: |
          bash scripts/posters.sh omigroup omigroup 4
          bash scripts/create-index.sh
          bash scripts/pdf.sh omigroup
          git config --global user.name "madjin"
          git config --global user.email "32600939+madjin@users.noreply.github.com"
          git add -A .
          git commit -m "update omigroup weekly notes"
          git push origin main
      
      - name: Update omigroup gltf-extensions
        run: |
          bash scripts/posters.sh omigroup gltf-extensions 4
          bash scripts/create-index.sh
          bash scripts/pdf.sh gltf-extensions
          git config --global user.name "madjin"
          git config --global user.email "32600939+madjin@users.noreply.github.com"
          git add -A .
          git commit -m "update omigroup gltf-extensions notes"
          git push origin main
