name: Run posters script

on:
  schedule:
    - cron: '0 0 * * 4' # Run every Thursday at midnight (PST)
    - cron: '0 0 * * 5' # Run every Friday at midnight (PST)

jobs:
  run_posters:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run posters script on Thursday
      if: github.event.schedule.cron == '0 0 * * 4'
      run: bash posters.sh omigroup omigroup

    - name: Run posters script on Friday
      if: github.event.schedule.cron == '0 0 * * 5'
      run: bash posters.sh omigroup gltf-extensions

    - name: Commit changes
      run: |
        git config --global user.name "madjin"
        git config --global user.email "32600939+madjin@users.noreply.github.com"
        git add -A .
        git commit -m "Run action runner"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main
