name: Run posters script

on:
  schedule:
    - cron: '0 0 * * 5' # Run every Friday at midnight
    - cron: '0 0 * * 6' # Run every Saturday at midnight

jobs:
  run_posters:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run posters script on Thursday
        if: github.event.schedule.cron == '0 0 * * 5'
        run: |
          bash scripts/posters.sh omigroup omigroup 4
          bash scripts/create-index.sh
          git config --global user.name "madjin"
          git config --global user.email "32600939+madjin@users.noreply.github.com"
          git add -A .
          git commit -m "Run action runner"
          git push origin main

      - name: Run posters script on Friday
        if: github.event.schedule.cron == '0 0 * * 6'
        run: |
          bash scripts/posters.sh omigroup gltf-extensions 4
          bash scripts/create-index.sh
          git config --global user.name "madjin"
          git config --global user.email "32600939+madjin@users.noreply.github.com"
          git add -A .
          git commit -m "Run action runner"
          git push origin main
