name: Run posters script

on:
  schedule:
    - cron: '59 23 * * 3' # Run every Wednesday at 11:59 PM
    - cron: '59 23 * * 4' # Run every Thursday at 11:59 PM

jobs:
  run_posters:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run posters script on Wednesday
        if: github.event.schedule == '59 23 * * 3'
        run: |
          bash scripts/posters.sh omigroup omigroup 4
          bash scripts/create-index.sh
          bash scripts/pdf.sh omigroup
          git config --global user.name "madjin"
          git config --global user.email "32600939+madjin@users.noreply.github.com"
          git add -A .
          git commit -m "Run action runner"
          git push origin main

      - name: Run posters script on Thursday
        if: github.event.schedule == '59 23 * * 4'
        run: |
          bash scripts/posters.sh omigroup gltf-extensions 4
          bash scripts/create-index.sh
          bash scripts/pdf.sh gltf-extensions
          git config --global user.name "madjin"
          git config --global user.email "32600939+madjin@users.noreply.github.com"
          git add -A .
          git commit -m "Run action runner"
          git push origin main
