name: Run posters script

on:
  schedule:
    - cron: '59 23 * * 4' # Run every Thursday at 11:59 PM

jobs:
  run_posters:
    runs-on: ubuntu-latest

    env:  # Add the environment variable here
      GITHUB_TOKEN: ${{ secrets.OMI_SECRET }}

    steps:
      - uses: actions/checkout@v3

      - name: Update omigroup
        run: |
          bash scripts/posters.sh omigroup omigroup 4
          bash scripts/create-index.sh
          bash scripts/pdf.sh omigroup
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A .
          git commit -m "update omigroup weekly notes"
      
      - name: Update omigroup gltf-extensions
        run: |
          bash scripts/posters.sh omigroup gltf-extensions 4
          bash scripts/create-index.sh
          bash scripts/pdf.sh gltf-extensions
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A .
          git commit -m "update omigroup gltf-extensions notes"
          git push origin main
